### ISSUE TITLE
Question about Lifetime-Amsi-EtwPatch

### ISSUE THREAD

**Issue by LikhonX** [EvilBytecode/Lifetime-Amsi-EtwPatch#1]
Hi! 😊 Your Lifetime-Amsi-EtwPatch project caught my eye. Amazing work on this go repository! ✨ Could you send me more details on [Telegram](https://t.me/nectariferous)? Also, please review my work and follow me on GitHub @nectariferous. Thanks!

**Comment by EvilBytecode** [comment]
Hello, your work is pretty mid, but effort is definietly there. just learn more about cybsec. if you want roadmap ;
https://roadmap.sh
[cyber-security.pdf](https://github.com/user-attachments/files/16182821/cyber-security.pdf)
